### ISSUE TITLE
Enabled by default

### ISSUE THREAD

**Issue by gotahistop** [marcussimonsen/let-it-snow.nvim#3]
Hi, is it possible to have snow enabled by default? ^_^
It's a very cute plugin, thanks!

**Comment by saattrupdan** [comment]
I added an auto command that enables it whenever I open a Python file and turns it off when I leave it - you could tweak it to your needs 🙂

https://github.com/saattrupdan/dotfiles/blob/main/nvim/lua/plugins/fun.lua

**Comment by gotahistop** [comment]
yeah i'll just autocmd it
